<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE definition [
<!ELEMENT definition (msg-info*) >
<!ELEMENT msg-info (category*) >
<!ATTLIST msg-info
    id ID #REQUIRED
    level CDATA #REQUIRED
    content CDATA #REQUIRED>
<!ELEMENT category (#PCDATA) >
]>

<definition>
    <msg-info id="DM0001E" level="ERROR"
            content="ログインIDもしくはパスワードが間違っています。">
    </msg-info>
    <msg-info id="DM0002E" level="ERROR"
            content="店番号：{0}、口座番号：{1}に一致する口座がありません。">
    </msg-info>

    <msg-info id="DM0003E" level="FATAL" 
        content="アプリケーションエラー：{0}" >
    </msg-info>

    <msg-info id="DM0004F" level="FATAL" 
        content="システムに問題があり処理を停止しました。" >
    </msg-info>
    
    <msg-info id="DM0001D" level="DEBUG"
        content="{0}メソッドを開始しました。">
    </msg-info>
    <msg-info id="DM0002D" level="DEBUG"
        content="{0}メソッドを終了しました。">
    </msg-info>

</definition>
