<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE definition [
<!ELEMENT definition (msg-info*) >
<!ELEMENT msg-info (category*,content*) >
<!ATTLIST msg-info
	id ID #REQUIRED
    level CDATA #REQUIRED
    errorCd CDATA #REQUIRED>
<!ELEMENT category (#PCDATA) >
<!ELEMENT content (#PCDATA) >
<!ATTLIST content
	locale CDATA #IMPLIED>
]>

<definition>

    <msg-info id="JFA0001T" level="TRACE" errorCd="1">
        <category>jfa</category>
        <content locale="ja">{0}メソッドを開始しました。</content>
    </msg-info>
    <msg-info id="JFA0002T" level="TRACE" errorCd="1">
        <category>jfa</category>
        <content locale="ja">{0}メソッドを終了しました。,{1}</content>
    </msg-info>
    <msg-info id="JFA0001D" level="DEBUG" errorCd="4">
        <category>jfa</category>
        <content locale="ja">[LayerLog   ]{0}</content>
    </msg-info>
    <msg-info id="JFA0002D" level="DEBUG" errorCd="4">
        <category>jfa</category>
        <content locale="ja">[JvmMemLog  ]{0},{1}</content>
    </msg-info>
    <msg-info id="JFA0003D" level="DEBUG" errorCd="4">
        <category>jfa</category>
        <category>performance</category>
        <content locale="ja">[PerformLog ]{0},{1}</content>
    </msg-info>
    <msg-info id="JFA0004D" level="DEBUG" errorCd="4">
        <category>jfa</category>
        <content locale="ja">[DataDumpLog]{0}{1}</content>
    </msg-info>
    <msg-info id="JFA0005D" level="DEBUG" errorCd="4">
        <category>jfa</category>
        <category>sql</category>
        <content locale="ja">[SQLLog     ]{0},{1}</content>
    </msg-info>
    <msg-info id="JFA0006D" level="DEBUG" errorCd="4">
        <category>jfa</category>
        <category>session</category>
        <content locale="ja">[SessionLog   ],{0}</content>
    </msg-info>
    <msg-info id="JFA0007D" level="DEBUG" errorCd="4">
        <category>jfa</category>
        <content locale="ja">入力情報に誤りがあります。</content>
    </msg-info>
    <msg-info id="JFA0001I" level="INFO" errorCd="7">
        <category>jfa</category>
        <content locale="ja">[TxStartLog ]{0},LoginUserID={1}</content>
    </msg-info>
    <msg-info id="JFA0002I" level="INFO" errorCd="7">
        <category>jfa</category>
        <content locale="ja">[TxEndLog   ]{0},LoginUserID={1},{2}</content>
    </msg-info>
    <msg-info id="JFA0001W" level="WARN" errorCd="10">
        <category>jfa</category>
        <content locale="ja">1度に取得する検索結果の上限値:{0}を超えた値:{1}を使用しています</content>
    </msg-info>
    <msg-info id="JFA0003E" level="ERROR" errorCd="16">
        <category>jfa</category>
        <content locale="ja">排他エラーが発生しました。対象データが他のトランザクションによって既に更新または削除されています。</content>
    </msg-info>
    <msg-info id="JFA0004E" level="ERROR" errorCd="16">
        <category>jfa</category>
        <content locale="ja">対象データが他のユーザーによって既に更新または削除されています。</content>
    </msg-info>
    <msg-info id="JFA0003F" level="FATAL" errorCd="16">
        <category>jfa</category>
        <content locale="ja">DBのロールバックに失敗しました。</content>
    </msg-info>
    <msg-info id="JFA0004F" level="FATAL" errorCd="16">
        <category>jfa</category>
        <content locale="ja">DBに関する問題が発生しました。</content>
    </msg-info>
    <msg-info id="JFA0005F" level="FATAL" errorCd="16">
        <category>jfa</category>
        <content locale="ja">システムに問題があり処理を停止しました。</content>
    </msg-info>
    <msg-info id="JFA0002W" level="WARN" errorCd="10">
        <category>jfa</category>
        <content locale="ja">[DataDumpLog]メモリが不足しているためダンプ処理を中断します。</content>
    </msg-info>
    <msg-info id="JFA0003W" level="WARN" errorCd="10">
        <category>jfa</category>
        <content locale="ja">[DataDumpLog]ダンプ処理中に想定外のエラーが発生しました。</content>
    </msg-info>
    <msg-info id="JFA0004W" level="WARN" errorCd="10">
        <category>jfa</category>
        <content locale="ja">Form情報の取得に失敗したため、処理をスキップします。</content>
    </msg-info>
    <msg-info id="JFA0005W" level="WARN" errorCd="10">
        <category>jfa</category>
        <content locale="ja">入力チェックエラーが検出された行番号の取得に失敗しました。</content>
    </msg-info>
    <msg-info id="JFA0008F" level="FATAL" errorCd="16">
        <category>jfa</category>
        <content locale="ja">不正なアクセスです。</content>
    </msg-info>
</definition>
